version: "3"

services:
  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: dotnet_app_production_postgres
    container_name: dotnet_app_local_postgres
    volumes:
      - dotnet_app_local_postgres_data:/var/lib/postgresql/data:Z
    networks:
      - dotnet_app_network
    expose:
      - "5432"
    env_file:
      - ./.envs/.local/.postgres

  api:
    build:
      context: .
      dockerfile: ./compose/local/dotnet/Dockerfile
    image: dotnet_app_local_api
    container_name: dotnet_app_local_api
    volumes:
      - .:/app
    networks:
      - dotnet_app_network
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    env_file:
      - ./.envs/.local/.dotnet
      - ./.envs/.local/.postgres
    command: /start

  nginx:
    build:
      context: .
      dockerfile: ./compose/local/frontend/Dockerfile
      args:
        - API_URL=http://localhost:8080/api
    image: dotnet_app_local_nginx
    container_name: dotnet_app_local_nginx
    volumes:
      - .:/app
    networks:
      - dotnet_app_network
    depends_on:
      - api
    ports:
      - "1234:1234"
    command: /start


volumes:
  dotnet_app_local_sqlserver_data: {}
  dotnet_app_local_postgres_data: {}

networks:
  dotnet_app_network:
    external: true
