version: "3"

services:
  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: dotnet_app_production_postgres
    container_name: dotnet_app_postgres
    volumes:
      - production_postgres_data:/var/lib/postgresql/data:Z
    expose:
      - 5432
    env_file:
      - ./.envs/.production/.postgres

  api:
    build:
      context: .
      dockerfile: ./compose/production/dotnet/Dockerfile
    image: dotnet_app_production_api
    container_name: dotnet_app_api
    depends_on:
      - postgres
    expose:
      - 8080
    env_file:
      - ./.envs/.production/.dotnet
      - ./.envs/.production/.postgres
    command: /start

  nginx:
    build:
      context: .
      dockerfile: ./compose/production/frontend/Dockerfile
      args:
        - API_URL=https://heh-api.serranomorante.com/api
    image: dotnet_app_production_nginx
    container_name: dotnet_app_nginx
    depends_on:
      - api
    expose:
      - 1234
    command: /start

  swag:
    # Swag
    # ---------------
    image: ghcr.io/linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Guayaquil
      - URL=serranomorantepatricio.info
      - SUBDOMAINS=dotnet,dotnet-api
      - VALIDATION=http
      - EMAIL=serranomorantepatricio@gmail.com
      - STAGING=True
    volumes:
      - ./config:/config
    ports:
      - 443:443
      - 80:80
    restart: unless-stopped


volumes:
  production_postgres_data: {}
