version: "3"

services:
  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: heh_shop_production_postgres
    container_name: heh_shop_postgres
    volumes:
      - production_postgres_data:/var/lib/postgresql/data:Z
    networks:
      - heh-shop-network
    expose:
      - "5432"
    env_file:
      - ./.envs/.production/.postgres

  api:
    build:
      context: .
      dockerfile: ./compose/production/dotnet/Dockerfile
    image: heh_shop_production_api
    container_name: heh_shop_api
    volumes:
      - heh-shop-app:/app
    networks:
      - heh-shop-network
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    env_file:
      - ./.envs/.production/.dotnet
      - ./.envs/.production/.postgres
    command: /start

  nginx:
    build:
      context: .
      dockerfile: ./compose/production/frontend/Dockerfile
      args:
        - API_URL=http://api:8080/api
    image: heh_shop_production_nginx
    container_name: heh_shop_nginx
    volumes:
      - heh-shop-app:/app
    networks:
      - heh-shop-network
    depends_on:
      - api
    ports:
      - "1234:1234"
    command: /start


volumes:
  heh-shop-api:
  heh-shop-app:
    external: true
  production_postgres_data: {}

networks:
  heh-shop-network:
    external: true
