version: '3'

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile.dev
      args:
        - VARIANT=6.0-bullseye
        - NODE_VERSION=lts/*
    container_name: dotnet_app_vscode_env
    init: true
    volumes:
      # The complete source code of our project
      - ..:/workspace:cached
      # Persist vscode extensions between reboots
      - vscode-extensions:/root/.vscode-server/extensions
    env_file:
      - ../.envs/.local/.dotnet
      - ../.envs/.local/.postgres
    networks:
      - dotnet_app_network

volumes:
  vscode-extensions:

# This external network is shared with the main docker-compose.yml config
# Ensures that services started from inside this dev container can all communicate
networks:
  dotnet_app_network:
    external: true
