#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

if [ -z "${POSTGRES_USER}" ]; then
    base_postgres_image_default_user='postgres'
    export POSTGRES_USER="${base_postgres_image_default_user}"
fi

export ConnectionStrings__DefaultConnection="Host=${POSTGRES_HOST};Database=${POSTGRES_DB};Port=${POSTGRES_PORT};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD};"


/wait-for postgres:5432 && exec "$@"
